server:
  port: 9000

spring:
  application:
    name: demo
    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: 5217966e19833aa5ffb27e605cf09515
              client-secret: EbJhjRxCE0EE7SDeIiHieHaPutqEJotX
              redirect-uri: http://localhost:9000/app/users/kakao
              authorization-grant-type: authorization_code
              client-authentication-method: POST
              client-name: Kakao
              scope:
                - profile_nickname
                - profile_image
                - profile_email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

  datasource:
    url: jdbc:mysql://temp-yanolja.cmpdjg7ch4e1.ap-northeast-2.rds.amazonaws.com/yanolja?autoReconnect=true
    username:  root
    password:  yanolja12
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
  sql:
    init:
      platform: mysql



