server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://temp-yanolja.cmpdjg7ch4e1.ap-northeast-2.rds.amazonaws.com/yanolja?autoReconnect=true # 변경해주세요
    username:  root
    password:  yanolja12
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
  sql:
    init:
      platform: mysql